POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Juhan Jalutaja",
  "number": "123 4567"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Mari Maasikas",
  "number": "987 6543"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Mihkel Pähkel",
  "number": "777 7777"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "no number"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "number": "no name"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "000-000000"
}